services:
  - type: web
    name: price-tracker-api
    env: node
    buildCommand: "npm ci && npm run build -w apps/api && npm run build -w services/price-tracker && npx playwright install --with-deps chromium"
    startCommand: "npm start -w apps/api"
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_NAME
        value: smart-price-tracker
      - key: DBURL
        sync: false
